# -*- coding: utf-8 -*-
"""Data Analyst Hiring Trends Analysis(code).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C6MBF-lEkGt-oVRv7b9RyPq7FNTopMyp
"""

# ==========================================
# DATA ANALYST HIRING TRENDS ANALYSIS
# ==========================================

# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
import os

# ==========================================
# DOWNLOAD DATASET
# ==========================================

path = kagglehub.dataset_download("andrewmvd/data-analyst-jobs")
print("Dataset Path:", path)

# Load Dataset
file_path = os.path.join(path, "DataAnalyst.csv")
df = pd.read_csv(file_path)

# ==========================================
# BASIC EXPLORATION
# ==========================================

print("Dataset Shape:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nFirst 5 Records:")
print(df.head())

print("\nMissing Values:")
print(df.isnull().sum())

# ==========================================
# TOP HIRING COMPANIES
# ==========================================

top_companies = df['Company Name'].value_counts().head(10)

plt.figure(figsize=(10,5))
top_companies.plot(kind='bar')
plt.title('Top 10 Hiring Companies')
plt.xlabel('Company Name')
plt.ylabel('Number of Job Postings')
plt.xticks(rotation=45)
plt.show()

# ==========================================
# TOP HIRING LOCATIONS
# ==========================================

top_locations = df['Location'].value_counts().head(10)

plt.figure(figsize=(10,5))
top_locations.plot(kind='bar')
plt.title('Top 10 Hiring Locations')
plt.xlabel('Location')
plt.ylabel('Number of Job Postings')
plt.xticks(rotation=45)
plt.show()

# ==========================================
# COMPANY RATING ANALYSIS
# ==========================================

plt.figure(figsize=(8,5))
df['Rating'].hist(bins=20)
plt.title('Company Rating Distribution')
plt.xlabel('Rating')
plt.ylabel('Count')
plt.show()

# ==========================================
# INDUSTRY ANALYSIS
# ==========================================

top_industries = df['Industry'].value_counts().head(10)

plt.figure(figsize=(10,5))
top_industries.plot(kind='bar')
plt.title('Top Industries Hiring Data Analysts')
plt.xlabel('Industry')
plt.ylabel('Number of Jobs')
plt.xticks(rotation=45)
plt.show()

# ==========================================
# COMPANY SIZE ANALYSIS
# ==========================================

plt.figure(figsize=(8,8))
df['Size'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)
plt.title('Company Size Distribution')
plt.ylabel('')
plt.show()

# ==========================================
# EASY APPLY ANALYSIS
# ==========================================

plt.figure(figsize=(6,6))
df['Easy Apply'].fillna('No').value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)
plt.title('Easy Apply Distribution')
plt.ylabel('')
plt.show()

# ==========================================
# SKILLS ANALYSIS
# ==========================================

skills = [
    'SQL',
    'Python',
    'Excel',
    'Tableau',
    'Power BI',
    'R',
    'AWS'
]

skill_count = {}

for skill in skills:
    count = df['Job Description'].str.contains(
        skill,
        case=False,
        na=False
    ).sum()

    skill_count[skill] = count

skill_df = pd.DataFrame(
    list(skill_count.items()),
    columns=['Skill','Count']
)

skill_df = skill_df.sort_values(
    by='Count',
    ascending=False
)

print("\nSkill Demand:")
print(skill_df)

plt.figure(figsize=(8,5))
plt.bar(skill_df['Skill'], skill_df['Count'])
plt.title('Most Demanded Skills')
plt.xlabel('Skill')
plt.ylabel('Demand Count')
plt.show()

# ==========================================
# ADD SKILL COLUMNS FOR POWER BI
# ==========================================

for skill in skills:
    df[skill] = df['Job Description'].str.contains(
        skill,
        case=False,
        na=False
    ).astype(int)

# ==========================================
# KPI METRICS
# ==========================================

total_jobs = len(df)
total_companies = df['Company Name'].nunique()
total_locations = df['Location'].nunique()
avg_rating = round(df['Rating'].mean(),2)

print("\n========== KPI METRICS ==========")
print("Total Jobs:", total_jobs)
print("Total Companies:", total_companies)
print("Total Locations:", total_locations)
print("Average Rating:", avg_rating)

# ==========================================
# EXPORT CLEANED DATASET
# ==========================================

df.to_csv("skills_jobs.csv", index=False)

print("\nFile Exported Successfully")
print("skills_jobs.csv")